#!/usr/bin/env bash


VECTOR_LENGHT="102400000"

OUTPUT_FILE="output_vectorAdd.txt"

LOOPS=$(seq 1 100)

date > $OUTPUT_FILE
for L in $LOOPS
do
  ./vectorAdd $VECTOR_LENGHT | tee -a $OUTPUT_FILE
done
