#!/usr/bin/env bash

LOOPS=$(seq 1 20)

VECTOR_LENGHT=$(seq 10000000 10000000 100000000)
SEGMENT_SIZE="2560"

OUTPUT_FILE="output_vectorAdd_stream_vector_length.txt"
date > $OUTPUT_FILE
for V_LEN in $VECTOR_LENGHT;
do
  for i in $LOOPS
  do
    ./vectorAdd-stream $V_LEN $SEGMENT_SIZE | tee -a $OUTPUT_FILE
  done
done

OUTPUT_FILE="output_vectorAdd_vector_length.txt"
date > $OUTPUT_FILE
for V_LEN in $VECTOR_LENGHT;
do
  for i in $LOOPS
  do
    ./vectorAdd $V_LEN $SEGMENT_SIZE | tee -a $OUTPUT_FILE
  done
done

VECTOR_LENGHT="100000000"
SEGMENT_SIZES="25600 128000 256000 1280000 2560000 12800000 25600000"

OUTPUT_FILE="output_vectorAdd_stream_segment_size.txt"
date > $OUTPUT_FILE
for S_SIZE in $SEGMENT_SIZES;
do
  for i in $LOOPS
  do
    ./vectorAdd-stream $VECTOR_LENGHT $S_SIZE | tee -a $OUTPUT_FILE
  done
done
